version: '3.8'

services:
  frontend:
    container_name: 'radio-plus-frontend'
    hostname: frontend
    ports:
      - '3000:3000'
    expose:
      - '3000'
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend-builder
      args:
        - NODE_ENV
        - API_BASE_URL
        - NEXT_PUBLIC_API_BASE_URL
        - NEXT_TELEMETRY_DISABLED
    env_file: 'apps/frontend/.env.prod'
    command: [ "npx", "next", "start" ]

  backend:
    container_name: 'radio-plus-backend'
    hostname: backend
    ports:
      - '3333:3333'
    expose:
      - '3333'
    build:
      context: .
      dockerfile: Dockerfile
      target: backend-builder
      args:
        - NODE_ENV
        - PORT
        - SPOTIFY_CLIENT_ID
        - SPOTIFY_CLIENT_SECRET
        - BACKEND_ORIGIN_URL
        - APP_ORIGIN_URL
        - CORS_ORIGINS
    env_file: 'apps/backend/.env.prod'
    command: ["node", "dist/apps/backend/main.js"]
