name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Connect your workspace on nx.app and uncomment this to enable task distribution.
      # The "--stop-agents-after" is optional, but allows idle agents to shut down once the "e2e-ci" targets have been requested
      # - name: Start CI run
      #   run: npx nx-cloud start-ci-run --distribute-on="5 linux-medium-js" --stop-agents-after="e2e-ci"

      # Cache node_modules
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Set SHAs
        uses: nrwl/nx-set-shas@v4

      - name: Record format
        run: npx nx-cloud record -- nx format:check
      - name: Run lint
        run: npx nx affected -t lint
      - name: Run test
        run: npx nx affected -t test --passWithNoTests
      - name: Run build
        run: npx nx affected -t build
      - name: Run e2e-ci
        run: npx nx affected -t e2e-ci
